site_name: Винтаж
site_description: Обучающие материалы для сотрудников

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: custom
      accent: custom
  font:
    text: Roboto
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Главная: index.md
  - Вина:
      - Шабли (Франция): wines/chablis.md
      - Соаве (Италия): wines/soave.md
      - Эгри Бикавер (Венгрия): wines/bikaver.md
  - Меню: menu.md
  - Подача вина: serving.md
